name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Java (Backend)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build backend
        run: |
          cd backend
          mvn clean package

      # Node (Frontend)
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build