name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Java backend
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build backend
        run: |
          cd ./backend
          mvn clean package

      # Node frontend
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd ./frontend
          ls   # debug (important)
          npm install

      - name: Build frontend
        run: |
          cd ./frontend
          npm run build